---
- name: Install R Studio Server
  yum:
    name: http://download2.rstudio.org/rstudio-server-rhel-0.99.441-x86_64.rpm
    state: present
  when: not custom_repo

- name: Install R Studio Server
  yum:
    name: rstudio-server
    state: present
  when: custom_repo

- name: Open port 8787 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 8787 -j ACCEPT"
  when: iptables_config

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config
