---
- name: Install dependencies
  yum:
    name: rrdtool
    state: present
  tags:
    - rstudio-server

- name: Install R Studio Server
  yum:
    name: "{{ rstudio_server_package_name }}"
    state: latest
    disable_gpg_check: yes
  tags:
    - rstudio-server
