---
- name: Install dependencies
  yum:
    name: rrdtool
    state: present

- name: Install R Studio Server
  yum:
    name: http://download2.rstudio.org/rstudio-server-rhel-0.99.473-x86_64.rpm
    state: present
  when: not custom_repo

- name: Install R Studio Server
  yum:
    name: rstudio-server
    state: present
    disable_gpg_check: yes
  when: custom_repo

- name: Install license
  command: rstudio-server license-manager activate {{ rstudio_server_key }}
  when: rstudio_server_key is defined
  notify:
    - restart rstudio-server

- name: Add ip whitelist
  template:
    src: ip-rules.j2
    dest: /etc/rstudio/ip-rules
  notify:
    - restart rstudio-server

- name: Add server config file
  template:
    src: rserver.conf.j2
    dest: /etc/rstudio/rserver.conf
  notify:
    - restart rstudio-server

- name: Open port 8787 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 8787 -s {{ hostvars[item]['ansible_ssh_host'] }} -j ACCEPT"
  when: iptables_config
  with_items: groups['proxy_server']

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config
