---
# TODO: fill this in
- name: ensure video driver
  shell: echo foo

- name: restart eod
  command: "{{ eod_install_directory }}/bin/otecs restart"

- name: restart gdm
  shell: killall gdm-binary && restart prefdm
