---
- name: Install zeromq repository
  template:
    src: zeromq.repo.j2
    dest: /etc/yum.repos.d/zeromq.repo
  tags:
    - zeromq
    - r

- name: Install zeromq
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zeromq
    - zeromq-devel
  tags:
    - zeromq
    - r
