---
- name: Install requirements
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-devel
    - python-psycopg2
    - git

- name: Ensure the temporary directory exists
  file:
    path: "{{ pp_temp_dir }}"
    recurse: yes
    state: directory

- name: Download PostgresPlus Advanced Server installer
  unarchive:
    src: "ppasmeta-{{ pp_installer_version }}-linux-x64.tar.gz"
    dest: "{{ pp_temp_dir }}/"
    mode: 0700

- name: Create configuration file
  template:
    src: config_param.j2
    dest: "{{ pp_temp_dir }}/config_param"
    mode: 0600

- name: Run PostgresPlus install script
  shell: "{{ pp_temp_dir }}/ppasmeta-{{ pp_installer_version }}-linux-x64/ppasmeta-{{ pp_installer_version }}-linux-x64.run --optionfile {{ pp_temp_dir }}/config_param"
  args:
    chdir: "{{ pp_temp_dir }}"
    creates: "{{ pp_prefix }}"
  notify:
    - restart postgres

- name: open up ports in iptables
  command: "iptables -I {{ iptables_chain }} 3 -p tcp -m tcp --dport {{ pp_serverport }} -j ACCEPT"
  when: iptables_config

- name: Ensure DBA service account exists
  postgresql_user:
    encrypted: yes
    login_user: "{{ pp_superaccount }}"
    login_password: "{{ pp_superpassword }}"
    name: "{{ pp_dba_username }}"
    password: "{{ pp_dba_password }}"
    port: "{{ pp_serverport }}"
    role_attr_flags: INHERIT,LOGIN,CREATEDB,CREATEROLE

- name: Create DBA service account DB
  postgresql_db:
    login_user: "{{ pp_superaccount }}"
    login_password: "{{ pp_superpassword }}"
    name: "{{ pp_dba_username }}"
    owner: "{{ pp_dba_username }}"
    state: present

- name: Grant the "postgres" role to DBA service account
  postgresql_privs:
    login: "{{ pp_superaccount }}"
    password: "{{ pp_superpassword }}"
    database: postgres
    port: "{{ pp_serverport }}"
    objs: postgres
    roles: "{{ pp_dba_username }}"
    type: group
    state: present

- name: Grant the dba_username account privileges on the public and pg_catalog schemas
  postgresql_privs:
    login: "{{ pp_superaccount }}"
    password: "{{ pp_superpassword }}"
    database: postgres
    port: "{{ pp_serverport }}"
    objs: "public,pg_catalog"
    privs: ALL
    roles: "{{ pp_dba_username }}"
    type: schema
    state: present
    grant_option: yes

- name: Grant the dba_username account privileges on pg_catalog tables
  postgresql_privs:
    login: "{{ pp_superaccount }}"
    password: "{{ pp_superpassword }}"
    database: postgres
    port: "{{ pp_serverport }}"
    objs: "pg_database,pg_authid"
    privs: ALL
    roles: "{{ pp_dba_username }}"
    type: table
    state: present
    grant_option: yes
    schema: pg_catalog

- name: Configure postgres connection options
  template:
    src: pg_hba.conf.j2
    dest: "{{ pp_datadir }}/pg_hba.conf"
    group: "{{ pp_superaccount }}"
    owner: "{{ pp_superaccount }}"
    mode: 0600

- name: Configure PPAS server
  template:
    src: postgresql.conf.j2
    dest: "{{ pp_datadir }}/postgresql.conf"
    group: "{{ pp_superaccount }}"
    owner: "{{ pp_superaccount }}"
    mode: 0600
