---
spark_tar_file: "spark-1.6.1-bin-without-hadoop.tgz"
spark_mirror: "http://apache.claz.org/spark/spark-1.6.1/spark-1.6.1-bin-without-hadoop.tgz"
spark_src_dir: "/usr/local/src"
spark_conf_dir: "/etc/spark"
spark_usr_parent_dir: "/usr/lib"  #spark extraction folder 
spark_main_dir: "/usr/lib/spark-1.6.1-bin-without-hadoop"       #symlink to the extracted/installed spark
spark_lib_dir: "/var/lib/spark"
spark_log_dir: "/var/log/spark"
spark_run_dir: "/run/spark"
spark_user: "spark"
spark_user_groups: []
spark_user_shell: "/bin/false"
spark_source_file: "/etc/profile.d/spark.sh"

spark_env_extras: {}
spark_defaults_extras: {}


