---
spark_version: "spark-1.6.0"
spark_mirror: "http://d3kbcqa49mib13.cloudfront.net"
#spark_mirror: "http://www.apache.org/dyn/closer.lua"
spark_src_dir: "/usr/local/src"
spark_conf_dir: "/etc/spark"
spark_usr_parent_dir: "/usr/lib"  #this is the folder where the spark archive will be extracted
spark_usr_dir: "/usr/lib/spark"   #this is the symlink to the extracted/installed spark
spark_lib_dir: "/var/lib/spark"
spark_log_dir: "/var/log/spark"
spark_run_dir: "/run/spark"
spark_user: "spark"
spark_user_groups: []
spark_user_shell: "/bin/false"

spark_env_extras: {}
spark_defaults_extras: {}


