---
- name: Install all rpms
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "{{gocd_rpms}}"

- name: Create the /usr/java directory
  file:
    path: /usr/java
    state: directory
    recurse: yes

- name: Symlink the jdk and jre directories
  file:
    src: "{{ java_home_path }}/"
    dest: /usr/java/{{ item }}
    state: link
  with_items:
    - jre
    - jdk

- name: Replace deployment.properties
  template:
    src: deployment.properties
    dest: /usr/java/jre/lib/deployment.properties
    mode: a+r

- name: Install go agent
  yum:
    name: "{{ gocd_local_bin_directory }}/go-agent-14.2.0-377.noarch"
    state: present

- name: Replace go-agent file
  template:
    src: go-agent
    dest: /etc/default/go-agent