---
- name: Install all dependencies
  yum:
    name: "{{item}}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "{{gocd_rpms}}"

- name: Copy over the go agent artifact
  copy:
    src: "{{ gocd_local_bin_directory }}/go-agent-14.2.0-377.noarch.rpm"
    dest: "{{ gocd_remote_bin_directory }}/go-agent-14.2.0-377.noarch.rpm"
  when: custom_repo

- name: Install go agent
  yum:
    name: "{{ gocd_remote_bin_directory }}/go-agent-14.2.0-377.noarch.rpm"
    state: present
  when: custom_repo

- name: Replace go-agent file
  template:
    src: go-agent
    dest: /etc/default/go-agent
