---
- name: Install postgres packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: postgres_packages

- name: Ensure other libraries can see header files
  file:
    src: {{ postgres_install_dir }}/include
    dest: /usr/include/include/pgsql
    state: link
    when: postgres_install_dir is defined
