# mesos-client-role.yml
---
- name: Add mesosphere repository
  command: rpm -Uvh http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6.2.noarch.rpm

- name: Install mesos package
  yum:
    name: mesos
    state: present

- name: Configure zookeeper with the IP's of all masters
  template:
    src: zk.j2
    dest: /etc/mesos/zk

- name: Disable mesos-master
  service:
    name: mesos-master
    state: stopped
    enabled: no

- name: Add the ip address to the mesos-master folder
  shell: "echo {{ ansible_eth0['ipv4']['address'] }} | sudo tee /etc/mesos-slave/ip"

- name: Add the ip to the hostname file too
  shell: "sudo cp /etc/mesos-slave/ip /etc/mesos-slave/hostname"

- name: Add isolation to mesos client config
  lineinfile:
    dest: /etc/defaults/mesos-slave
    line: ISOLATION=cgroups/cpu,cgroups/mem
    regexp: ^ISOLATION=
    state: present

- name: Configure correct cgroups route
  shell: "echo '/cgroups' | sudo tee /etc/mesos-slave/cgroups_hierarchy"

- name: Open required ports
  command: "iptables -I {{ iptables_chain }} 2 -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 2181
    - 5050
    - 5051

- name: Save iptables
  command: "/sbin/service iptables save"
  notify:
    - restart iptables
###
# zk.j2 contents
#
# zk://{% for host in groups['mesos_masters'] %}{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}:2181{% if not forloop.last %},{% endif %}{% endfor %}/mesos
