# mesos-client-role.yml
---
- name: Add mesosphere repository
  command: "rpm -Uvh http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm"
  args:
    creates: /etc/yum.repos.d/mesosphere.repo

- name: Install mesos package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mesos
    - libselinux-python

- name: Configure zookeeper with the IP's of all masters
  template:
    src: zk.j2
    dest: /etc/mesos/zk
  notify:
    - restart mesos-client

- name: Add the ip address to the Mesos client config folder
  shell: "echo {{ ansible_ssh_host }} | sudo tee /etc/mesos-slave/ip"
  notify:
    - restart mesos-client


- name: Add the ip to the hostname file too
  shell: "sudo cp /etc/mesos-slave/ip /etc/mesos-slave/hostname"
  notify:
    - restart mesos-client

- name: Stop the Mesos master process
  command: "stop mesos-master"
  register: mesos_master_stop
  failed_when: mesos_master_stop.rc != 0 and 'Unknown instance' not in mesos_master_stop.stderr

- name: Override the mesos-master service
  file:
    dest: /etc/init/mesos-master.conf.override
    state: touch

- name: Add the ip address to the mesos client folder
  shell: "echo {{ ansible_ssh_host }} | sudo tee /etc/mesos-slave/ip"
  notify:
    - restart mesos-client

- name: Add the ip to the hostname file too
  shell: "sudo cp /etc/mesos-slave/ip /etc/mesos-slave/hostname"
    notify:
    - restart mesos-client

- name: Add isolation to mesos client config
  lineinfile:
    dest: /etc/defaults/mesos-slave
    line: ISOLATION=cgroups/cpu,cgroups/mem
    regexp: ^ISOLATION=
    state: present
    create: yes
  notify:
    - restart mesos-client

- name: Configure correct cgroups route
  shell: "echo '/cgroups' | sudo tee /etc/mesos-slave/cgroups_hierarchy"
  notify:
    - restart mesos-client

- name: Open required ports
  command: "iptables -I {{ iptables_chain }} 2 -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 5051
  when: iptables_config

- name: Save iptables
  command: "/sbin/service iptables save"
  when: iptables_config
  notify:
    - restart iptables

- name: Start the Mesos client
  command: "start mesos-slave"
  register: mesos_client_start
  failed_when: mesos_client_start.rc != 0 and 'Job is already running' not in mesos_client_start.stderr

