# mesos-agent/main.yml
---

### SETUP MESOS REPOSITORIES AND INSTALL

- name: Add mesosphere repository
  command: "rpm -Uvh http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm"
  args:
    creates: /etc/yum.repos.d/mesosphere.repo

- name: Install mesos package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mesos
    - libselinux-python

- name: Stop the Mesos master process
  command: "stop mesos-master"
  register: mesos_master_stop
  failed_when: mesos_master_stop.rc != 0 and 'Unknown instance' not in mesos_master_stop.stderr

- name: Override the mesos-master service
  file:
    dest: /etc/init/mesos-master.conf.override
    state: touch

### CONFIGURE MESOS AGENT

- name: Configure zookeeper with the IP's of all masters
  template:
    src: zk.j2
    dest: /etc/mesos/zk
  notify:
    - restart mesos-agent

- name: Add the ip address to the Mesos agent config folder
  copy:
    dest: /etc/mesos-slave/ip
    content: "{{ ansible_ssh_host }}"
  notify:
    - restart mesos-agent

- name: Add the ip to the hostname file too
  copy:
    dest: /etc/mesos-slave/hostname
    content: "{{ ansible_ssh_host }}"
  notify:
    - restart mesos-agent

- name: Configure port for Mesos to run on
  copy:
    dest: /etc/mesos-slave/port
    content: "{{ mesos_agent_port }}"
  notify:
    - restart mesos-agent

- name: Add isolation to mesos client
  copy:
    dest: /etc/mesos-slave/isolation
    content: "{{ mesos_agent_isolation }}"
  notify:
    - restart mesos-agent

- name: Configure correct cgroups route
  copy:
    dest: /etc/mesos-slave/cgroups_hierarchy
    content: "{{ mesos_agent_cgroups_path }}"
  notify:
    - restart mesos-agent

- name: Create credential file, if needed
  copy:
    dest: "{{ mesos_agent_credential }}"
    content: "{{ mesos_agent_principal }} {{ mesos_agent_secret }}"
  when: mesos_agent_credential is defined
  notify:
    - restart mesos-agent

- name: Configure Mesos agent to use credential
  copy:
    dest: /etc/mesos-slave/credential
    content: "{{ mesos_agent_credential }}"
  when: mesos_agent_credential is defined
  notify:
    - restart mesos-agent

- name: Make mesos working directory
  file:
    dest: "{{ mesos_agent_work_dir }}"
    state: directory
    mode: 0755

- name: Configure working directory
  copy:
    dest: /etc/mesos-slave/work_dir
    content: "{{ mesos_agent_work_dir }}"
  notify:
    - restart mesos-agent

### SETUP IP TABLES AND START MESOS AGENT

- name: Open required ports
  command: "iptables -I {{ iptables_chain }} 2 -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 5051
  when: iptables_config

- name: Save iptables
  command: "/sbin/service iptables save"
  when: iptables_config
  notify:
    - restart iptables

- name: Start the Mesos agent
  command: "start mesos-slave"
  register: mesos_agent_start
  failed_when: mesos_agent_start.rc != 0 and 'Job is already running' not in mesos_agent_start.stderr
