---
- name: Verify install directory
  file: 
    path: "{{sublime_install_directory}}/"
    state: directory

- name: Unarchive sublime
  unarchive:
    src: "{{ sublime_local_artifact_directory }}/Sublime_Text_2.0.2_x64.tar.bz2"
    dest: "{{ sublime_install_directory }}/"