---
- name: Intall OpenSSL
  yum:
    name: openssl098e
    state: present

- name: Check if RStudio Server Pro is installed
  command: rpm -q rstudio-server
  ignore_errors: yes
  register: rstudio_server_rpm_check

- name: Get RStudio RPM
  command: "wget http://download2.rstudio.org/rstudio-server-pro-0.98.1103-x86_64.rpm"
  when: rstudio_server_rpm_check.rc != 0

- name: Install RStudio Server Pro
  yum:
    name: rstudio-server-pro-0.98.1103-x86_64.rpm
    state: present
  when: rstudio_server_rpm_check.rc != 0

- name: Copy RStudio to PAM
  template: 
    src: rstudio
    dest: /etc/pam.d/rstudio

- name: Ensure port 8787 open
  command: "iptables -I {{ iptables_chain }} 3 -p tcp -m tcp --dport 8787 -j ACCEPT"
  when: iptables_config
