# main.yml - Nginx installation
---
- name: Install Nginx
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Create Nginx user, if needed
  user:
    name: "{{ nginx_user }}"
    comment: "Nginx User"

- name: Configure
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_dir }}/nginx.conf"
    mode: 0640

- name: Ensure permissions are correct to view logs
  file:
    dest: "{{ nginx_log_dir }}"
    mode: 0755
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Ensure Nginx is started and enabled at boot time.
  service:
    name: nginx
    state: started
    enabled: yes

- name: Open port 80 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 80 -j ACCEPT"
  when: iptables_config

- name: Open port 443 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 443 -j ACCEPT"
  when: iptables_config

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config
