---
- name: Install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - R-core
    - R-devel
    - blas
    - blas-devel
    - lapack
    - lapack-devel
    - texinfo
    - texinfo-tex
    - libicu
    - libicu-devel

- name: Install R packages
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) install.packages(pkgs='{{item}}', repos=c('http://cran.rstudio.com/'))"
  with_items: r_packages
