---
- name: Install base packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - R-core
    - R-devel
    - blas
    - blas-devel
    - lapack
    - lapack-devel
    - texinfo
    - texinfo-tex
    - libicu
    - libicu-devel