---
- name: Install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - R-core
    - R-devel
    - blas
    - blas-devel
    - lapack
    - lapack-devel
    - texinfo
    - texinfo-tex
    - libicu
    - libicu-devel

- name: Install packages required by R packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: r_dependencies

- name: Install R packages
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', INSTALL_opts=c('--no-test-load'),repos=c('http://cran.rstudio.com/')); print('Added'); } else { print('Already installed'); }"
  with_items: r_packages
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  environment: r_env_vars
