---
- name: Install license
  command: rstudio-server license-manager activate {{ rstudio_server_key }}
  when: rstudio_server_key is defined
  notify:
    - restart rstudio-server

- name: Add ip whitelist
  template:
    src: ip-rules.j2
    dest: /etc/rstudio/ip-rules
  notify:
    - restart rstudio-server

- name: Add server config file
  template:
    src: rserver.conf.j2
    dest: /etc/rstudio/rserver.conf
  notify:
    - restart rstudio-server
