# configure_file_shares.yml - Setup shared volumes in GlusterFS
# This configuration is specific to the default configuration
# used by Vagrant, and so should not be used for a real deployment
# without extensive modification.
---
- hosts: file_server_2
  sudo: yes

  tasks:
    - name: Probe for other file server
      command: "gluster peer probe 10.0.1.4"

    - name: Create volume
      command: "gluster volume create {{ item }} replica 2 transport tcp 10.0.1.4:/data/{{ item }} 10.0.1.5:/data/{{ item }}"
      with_items: shared_folders

    - name: Start the volume
      command: "gluster volume start {{ item }}"
      with_items: shared_folders
