---
- hosts: elk
  sudo: yes
  roles:
    - common
    - {role: puppet_disable, when: "disable_puppet"}
    - {role: iptables, when: "iptables_config"}
    - {role: epel, when: "not 'production' in group_names"}
    - jdk
    - elasticsearch
    - elasticsearch-config
    - logstash
    - logstash-config
    - kibana
    - kibana-config
    - {role: log-courier, when: "install_logstash"}

- hosts: elk
  sudo: yes
  handlers:
    - include: roles/shared/handlers/main.yml
  tasks:
    - name: Setup elasticsearch as a client node
      lineinfile:
        dest: /etc/elasticsearch/elasticsearch.yml
        regexp: '^(#)?\s+"{{ item }}":'
        line: "{{ item }}: false"
        state: present
      with_items:
        - "node.master"
        - "node.data"
      notify:
        - restart elasticsearch
