---
- hosts: research_environment
  sudo: yes
  roles:
    - {role: iptables, when: "iptables_config"}
    - {role: common, when: "install_glusterfs"}
    - {role: python, when: "custom_repo"}
    - {role: python-build, when: "not custom_repo"}
    - {role: odbc, when: "install_odbc"}

- hosts: research_ancillary_services
  sudo: yes
  roles:
    - emacs
    - open_office
    - evince
    - stattransfer
  tasks:
    - name: Install Ultra Edit
      yum:
        name: UltraEdit.x86_64
        state: present
        disable_gpg_check: yes

- hosts: research_eod
  sudo: yes
  roles:
    - eod

- hosts: research_gauss
  sudo: yes
  roles:
    - gauss

- hosts: research_stata
  sudo: yes
  roles:
    - stata
    - eod

- hosts: research_python
  sudo: yes
  roles:
    - r-studio-desktop
    - r-studio-server
    - pycharm