---
- hosts: analytics_terminal
  sudo: yes
  roles:
    - {role: iptables, when: "iptables_config"}
    - {role: common, when: "install_glusterfs"}
    - {role: epel, when: "use_epel"}

  # Install development packages
- hosts: analytics_terminal
  sudo: yes
  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "@development"
        - gcc-gfortran
        - postgresql
        - postgresql-devel
        - python-devel
        - nodejs

    - name: Install custom RPMs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - xsv
        - gnucobol
      when: custom_repo

    - name: Activate Julia repo
      get_url:
        url: https://copr.fedoraproject.org/coprs/nalimilan/julia/repo/epel-6/nalimilan-julia-epel-6.repo
        dest: /etc/yum.repos.d/nalimilan-julia-epel-6.repo
      when: not custom_repo

    - name: Install Julia
      yum:
        name: julia
        state: present

- hosts: analytics_terminal
  sudo: yes
  roles:
    - {role: python, when: "custom_repo"}
    - {role: python-build, when: "not custom_repo"}
    - {role: eod, when: "install_eod"}
    - jdk
    - r
    - revolution-r
    - ruby
    - r-shiny
    - r-studio-desktop
    - r-studio-server
    - {role: logstash-forwarder, when: "install_logstash"}

- hosts: analytics_terminal
  sudo: yes
  tasks:
    - name: Open port range for app prototyping
      command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 8000:8100 -s {{ hostvars[item]['ansible_ssh_host'] }} -j ACCEPT"
      when: iptables_config
      with_items: groups['proxy_server']

    - name: Save rules
      command: "/sbin/service iptables save"
      when: iptables_config