---
logstash_es_output_file: 30-elasticsearch-output.conf.j2
logstash_user: logstash
logstash_password: password
logstash_filters:
  -
    name: 12-example-filter.conf
    content: >
      filter {
        date {
          match => [ "timestamp", "ISO8601" ]
        }
      }
