---
- name: Verify install directory
  file: 
    path: "{{pycharm_install_directory}}/"
    state: directory

- name: Untar tarball
  unarchive: 
    src: "{{ pycharm_local_bin_directory }}/pycharm-community-4.5.1.tar.gz"
    dest: "{{ pycharm_install_directory }}"
