---
- name: Download PyCharm tarball
  command: wget http://download.jetbrains.com/python/pycharm-community-4.5.1.tar.gz

- name: Unpack tarball
  command: tar xfz pycharm-community-4.5.1.tar.gz

- name: Remove tarball
  command: rm pycharm-community-4.5.1.tar.gz