# main.yml - Common configuration for all servers within the data platform

### FUNCTIONS
# Sets up access to RH GlusterFS shared volumes, and mounts them
---
- name: Ensure that FUSE is enabled
  modprobe:
    name: fuse
    state: present

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs
    - glusterfs-fuse
    - libselinux-python

- name: Make needed folders
  file:
    state: directory
    dest: "/home/{{ item }}"
    mode: 0777
  with_items: shared_folders

# Temporary work around, since GlusterFS FUSE does
# not support '-o remount'
- name: Unmount the shared drives
  mount:
    fstype: glusterfs
    name: "/home/{{ item }}"
    src: "{{ default_file_server }}:/{{ item }}"
    state: unmounted
  with_items: shared_folders

- name: Mount shared drives and add to fstab
  mount:
    fstype: glusterfs
    name: "/home/{{ item }}"
    src: "{{ default_file_server }}:/{{ item }}"
    state: mounted
  with_items: shared_folders
