# main.yml - Common configuration for all servers within the data platform

### FUNCTIONS
# Sets up access to RH GlusterFS shared volumes, and mounts them
---
- name: Ensure that FUSE is enabled
  modprobe:
    name: fuse
    state: present

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs
    - glusterfs-fuse
    - libselinux-python

- name: Make needed folders
  file:
    state: directory
    dest: "/home/{{ item.name }}"
    mode: 0777
  with_items: shared_folders
  when: item.state == 'mounted'

# Temporary work around, since GlusterFS FUSE does
# not support '-o remount'
#- name: Determine which drives are in use
#  shell: "fuser -c /home/{{ item }}"
#  register: volume_status
#  with_items: shared_folders
#  failed_when: volume_status.stderr != ""

- name: Unmount the shared drives
  mount:
    fstype: glusterfs
    name: "/home/{{ item.name }}"
    src: "{{ default_file_server }}:/{{ item.name }}"
    state: unmounted
  with_items: shared_folders
  when: item.state == 'mounted'

  # when: not "production" in group_names
  # ignore_errors: yes

#  with_items: "{{ volume_status.results }}"
#  when: item.rc == 1

- name: Mount shared drives and add to fstab
  mount:
    fstype: glusterfs
    name: "/home/{{ item.name }}"
    src: "{{ default_file_server }}:/{{ item.name }}"
    state: "{{ item.state }}"
    opts: "defaults,acl,_netdev"
  with_items: shared_folders

- name: Remove unneeded folders
  file:
    state: absent
    dest: "/home/{{ item.name }}"
  with_items: shared_folders
  when: item.state == 'unmounted'
