---
- name: Install libgcc
  yum:
    name: libgcc.i686
    state: present

- name: Install glibc
  yum:
    name: glibc.i686
    state: present

- name: Install atk
  yum:
    name: atk.i686
    state: present

- name: Install gdk-pixbuf2
  yum:
    name: gdk-pixbuf2.i686
    state: present

- name: Install fontconfig
  yum:
    name: fontconfig.i686
    state: present

- name: Install mesa-libGL
  yum:
    name:  mesa-libGL.i686
    state: present

- name: Install mesa-libGLU
  yum:
    name: mesa-libGLU.i686
    state: present

- name: Install pango
  yum:
    name: pango.i686
    state: present

- name: Install libxml2
  yum:
    name: libxml2.i686
    state: present

- name: Install libidx
  yum:
    name: libidn.i686
    state: present

- name: Install libXt
  yum:
    name: libXt.i686
    state: present

- name: Install gtk2
  yum:
    name: gtk2.i686
    state: present

- name: Install AdobeReader
  yum: 
    name: http://linuxdownload.adobe.com/linux/i386/AdbeRdr9.5.4-1_i486linux_enu.rpm
    state: present
  when: not custom_repo

- name: Install AdobeReader
  yum:
    name: AdobeReader_enu
    state: present
  when: custom_repo

- name: Install libcanberra-gtk2
  yum:
    name: libcanberra-gtk2.i686
    state: present

- name: Install PackageKit-gtk-module
  yum:
    name: PackageKit-gtk-module.i686
    state: present

- name: Install gtk2-engines
  yum:
    name: gtk2-engines.i686
    state: present

# NOTE: Sean did not include this, but I assume we need to actually do it, since we at no point actually install evince
- name: Install evince
  yum:
    num: evince
    state: present