---
- name: Install libgcc
  yum:
    name: libgcc
    state: present

- name: Install glibc
  yum:
    name: glibc
    state: present

- name: Install atk
  yum:
    name: atk
    state: present

- name: Install gdk-pixbuf2
  yum:
    name: gdk-pixbuf2
    state: present

- name: Install fontconfig
  yum:
    name: fontconfig
    state: present

- name: Install mesa-libGL
  yum:
    name:  mesa-libGL
    state: present

- name: Install mesa-libGLU
  yum:
    name: mesa-libGLU
    state: present

- name: Install pango
  yum:
    name: pango
    state: present

- name: Install libxml2
  yum:
    name: libxml2
    state: present

- name: Install libidx
  yum:
    name: libidn
    state: present

- name: Install libXt
  yum:
    name: libXt
    state: present

- name: Install gtk2
  yum:
    name: gtk2
    state: present

- name: Install AdobeReader
  yum: 
    name: http://linuxdownload.adobe.com/linux/i386/AdbeRdr9.5.4-1_i486linux_enu.rpm
    state: present
  when: not custom_repo

- name: Install AdobeReader
  yum:
    name: AdobeReader_enu
    state: present
  when: custom_repo

- name: Install libcanberra-gtk2
  yum:
    name: libcanberra-gtk2
    state: present

- name: Install PackageKit-gtk-module
  yum:
    name: PackageKit-gtk-module
    state: present

- name: Install gtk2-engines
  yum:
    name: gtk2-engines
    state: present

# NOTE: Sean did not include this, but I assume we need to actually do it, since we at no point actually install evince
- name: Install evince
  yum:
    name: evince
    state: present