---
- name: Download intellij
  get_url: 
    url: "{{ intellij_url }}"
    dest: "/tmp/intellij-{{ intellij_version }}"
  tags: 
  - intellij

- name: Create install directory
  file:
    path: "{{ intellij_install_dir }}"
    state: directory
    mode: 0755
  tags:
  - intellij

- name: Extract intellij from /tmp 
  unarchive:
    src: "/tmp/intellij-{{ intellij_version }}"
    dest: "{{ intellij_install_dir }}"
    copy: no 
  tags:
  - intellij

- name: Create symlink for idea.sh
  file:
    src: "{{ intellij_install_dir }}/idea-IC-145.1617.8/bin/idea.sh"
    dest: "{{ intellij_main_dir }}/bin/idea.sh"
    state: link
  tags:
  - intellij 

- name: Install Intellij IDEA desktop file
  template:
    src: idea.desktop.j2
    dest: "{{ inteillij_desktop_dir }}/idea.desktop"
    mode: 0644
  tags:
  - intellij

- name: Set up idea.png
  template:
    src: idea.png.j2
    dest: "{{ intellij_main_dir }}/bin"
  tags:
  - intellij

