---
- name: Install postgres repository
  yum:
    name: "{{ postgres_repository_url }}"
    state: present
  when: postgres_install_repository

- name: Install postgres repository key
  rpm_key:
    key: "{{ postgres_repository_key_url }}"
    state: present
  when: postgres_install_repository

- name: Ensure older versions are removed
  yum:
    name: postgresql
    state: absent
    disablerepo: "{{ postgres_respository_name }}"
  ignore_errors: yes
  when: clean_postgresql

- name: Install postgres packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgres_packages }}"

- name: Ensure other libraries can see header files
  file:
    src: "{{ postgres_install_dir }}/include/"
    dest: /usr/include/pgsql
    state: link

- name: Ensure other libraries can see library files
  file:
    src: "{{ postgres_install_dir }}/lib"
    dest: /usr/lib/pgsql
    state: link

- name: Add psql bin directory to path
  lineinfile:
    dest: /etc/profile.d/postgres.sh
    create: yes
    line: export PATH={{ postgres_install_dir }}/bin:$PATH
    mode: 0644
