# main.yml - Activate EPEL
---
- name: Install EPEL repo
  yum:
    name: "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
    state: present

- name: Import the EPEL GPG key
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6"
    state: present
