---
odbc_host_1: odbc_host_1
odbc_host_1_fqdn: odbc_host_1.example.com
odbc_host_2: odbc_host_2
odbc_host_2_fqdn: odbc_host_2.example.com
odbc_host_3: odbc_host_3
odbc_host_3_fqdn: odbc_host_3.example.com
odbc_host_4: odbc_host_4
odbc_host_4_fqdn: odbc_host_4.example.com

odbc_ms_sql_hostname: host_ms_sql
odbc_entries:
  - {
    hostname: host1,
    Server: host1.example.com,
    Description: /usr/lib64/libtdsodbc.so,
    Driver: /usr/lib64/libtdsodbc.so
  }

  - {
    hostname: host2,
    Server: host2.example.com,
    Description: /usr/lib64/libtdsodbc.so,
    Driver: /usr/lib64/libtdsodbc.so
  }

  - {
    hostname: host3,
    Server: host3.example.com,
    Description: /usr/lib64/libtdsodbc.so,
    Driver: /usr/lib64/libtdsodbc.so
  }

freetds_entries:
  - {
    hostname: odbc_host_1,
    fqdn: odbc_host_1.example.com,
    use_ntlmv2: True
  }

  - {
    hostname: odbc_host_2,
    fqdn: odbc_host_2.example.com,
    use_ntlmv2: False
  }