# main.yml - Default variables for testing
---

# Real variables should be placed in respective environment directories within
# the group_vars folder, for example /group_vars/development

### GENERAL SETTINGS ###
#======================#

# Allow custom iptables chain to be used, if needed
iptables_chain: INPUT

# Specifies which file server to connect to, doesn't really matter which one
# you use.
default_file_server: 10.0.1.4

# Define all GlusterFS "bricks" you want here.  Folders will be created on the
# file server based on these settings, and GlusterFS volumes will be created and
# mounted on client servers.
shared_folders:
  - "data"
  - "work"
  - "testorg"

# Allows servers to use one of the GlusterFS volumes as a shared home directory
home_directory: "/testorg"

# Adds a customizeable masthead to all configuration files deployed by Ansible.
template_masthead: >
  #=======================================================\N
  # Test Organization\N
  #-------------------------------------------------------\N
  #\N
  # This file was generated by Ansible, any changes will\N
  # be overwritten.\N
  #\N

# Custom RPM repository, if used
custom_repo: 

