# main.yml - Default variables for testing
---

# Real variables should be placed in respective environment directories within
# the group_vars folder, for example /group_vars/development

#======================#
### GENERAL SETTINGS ###
#======================#

# Specifies which file server to connect to, doesn't really matter which one
# you use.
default_file_server: 10.0.1.4

# Define all GlusterFS "bricks" you want here.  Folders will be created on the
# file server based on these settings, and GlusterFS volumes will be created and
# mounted on client servers.
shared_folders:
  - "data"
  - "work"
  - "testorg"

# Allows servers to use one of the GlusterFS volumes as a shared home directory
home_directory: "/testorg"

# Adds a customizeable masthead to all configuration files deployed by Ansible.
template_masthead: |
  #=======================================================
  # Test Organization
  #-------------------------------------------------------
  #
  # This file was generated by Ansible, any changes will
  # be overwritten.
  #

# Human readable org name
organization_name: "Test Organization"

# Geography
country: US
state: DC
city: Washington

# Determines if custom RPMS can be installed, or need to be built
custom_repo: False

# Toggle whether or not to install GlusterFS clients
install_glusterfs: True

# Toggle whether or not to install EOD
# NOTE: If set to yes, you must provide the EOD binary file
# and a license key or license server.  The default is off
# for this reason
install_eod: False

#==============#
### IPTABLES ###
#==============#

# Enable or disable the configuration of iptables rules
iptables_config: True

# Allow custom iptables chain to be used, if needed
iptables_chain: TEST-INPUT

# This list of dictonaries defines global IP tables rules
iptables_standard:
  - 
    port: 22
    protocol: tcp

subnet: 0.0.0.0/0

#===================#
### HTTP SETTINGS ###
#===================#

# Global domain name and TLD
domain_name: test.dev

# Settings for the proxy server
proxy_subdomain: proxy

# Whether or not to enable SSL
enable_ssl: True
generate_certs: True
ssl_cert_file: /etc/httpd/ssl/apache.crt
ssl_key_file: /etc/httpd/ssl/apache.key
ssl_chain_file: /etc/httpd/ssl/apache.crt

#=======================#
### KERBEROS SETTINGS ###
#=======================#

# Whether or not the HTTP keytab must be created
# Should only be "True" when using Vagrant
create_keytabs: True

# Primary Realm name
default_realm_name: TEST.DEV

# The KDC Server
kdc_domain_name: kdc.test.dev

# KRB Service user, if available
krb_service_user: testuser
krb_service_user_password: password

# Enable or disable mapping of Kerberos user principles to regular usernames
krb_user_mapping: "Off"

# Name of the HTTP keytab file
keytab_filename: http.keytab

# List of dictionaries for each Kerberos Realm
realms:
  - name: TEST.DEV
    domain_name: test.dev
    kdc_domain_name: kdc.test.dev:88
    admin_domain_name: kdc.test.dev:749

# Whether or not to ask for password when using HTTP auth
krb_ask_pass: "On"

#===================#
### LDAP SETTINGS ###
#===================#

# LDAP Server
ldap_subdomain: ldap
ldap_server: kdc.test.dev

# LDAP Service Account
ldap_service_account: admin
ldap_service_account_password: password

# App specific settings

# For the proxy server test page
restricted_group_name: admin

# Research Environment
install_evince: True
install_pycharm: True
install_gauss: True
install_stata: True