---
- name: Setup configuration
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_config_path }}/kibana.yml"
  notify:
    - restart kibana

- name: Install kibana plugins
  command: /opt/kibana/bin/kibana plugin --install {{ item }}
  with_items: "{{ kibana_plugins }}"
  register: kibana_result
  failed_when: kibana_result.rc == 0 and "already exists" not in kibana_result.stderr

- name: Start Kibana
  service:
    name: kibana
    state: started
