# main.yml - Apache installation and setup
---
- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl
    - openssh
    - php
    - php-common
    - php-ldap

# We ignore errors here, since the actual host configuration
# will happen elsewhere in the playbook, so error states should
# be corrected later, at which point Apache will trigger an
# error if things still aren't correct.
- name: Ensure Apache is started and enabled on boot.
  service:
    name: httpd
    state: started
    enabled: yes
  failed_when: False

- name: Open port 80 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 80 -j ACCEPT"
  when: iptables_config

- name: Open port 443 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 443 -j ACCEPT"
  when: iptables_config

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config
