# main.yml - Apache installation and setup
---
- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl
    - openssh
    - php
    - php-common
    - php-ldap

- name: Ensure Apache is started and enabled on boot.
  service:
    name: httpd
    state: started
    enabled: yes

- name: Open port 80 in iptables
  command: "iptables -A {{ iptables_chain }} -m state --state NEW -p tcp --dport 80 -j ACCEPT"

- name: Open port 443 in iptables
  command: "iptables -A {{ iptables_chain }} -m state --state NEW -p tcp --dport 443 -j ACCEPT"

- name: Save rules
  command: "/sbin/service iptables save"
