# main.yml
---
#- name: Add mpapis public key
#  shell: "curl -sSL https://rvm.io/mpapis.asc | gpg --import -"

- name: Add mpapis public key
  rpm_key:
    state: present
    key: https://rvm.io/mpapis.asc

- name: Install RVM and stable Ruby
  shell: "curl -sSL https://get.rvm.io | sudo bash -s stable --ruby"
  args:
    creates: /usr/local/rvm/bin/rvm
