---
#==================#
### EoD SETTINGS ###
#==================#
eod_install_directory: '/usr/local/eod'
eod_local_bin_directory: /vagrant
eod_bin_directory: '/tmp'
eod_client_ports:
  - 5500
  - 8406
  - 8407
eod_cm_password: PASSWORD
eod_cm_preferred_pcm: "{{ ansible_ssh_host }}"
cluster_name: "{{ ansible_ssh_host }}"

xdmc_query_host: "{{ ansible_ssh_host }}"
eod_use_license_server: 0
eod_license_server_host:
eod_license_server_cache: cache.text.dev
# TODO: you can put all the keys you want to here
eod_license_keys:
  - XXXX-YYYYYY-ZZZZZZ-AAAA-BBBBBB-CCC -1234567890 123